export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls --color=auto'
# Source all the zsh plugins from .cfg/zsh_plugins/*
source "$HOME/.cfg/zsh_plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh"
source "$HOME/.cfg/zsh_plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$HOME/.cfg/zsh_plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
# Color for vim
source "$HOME/.cfg/cfgfiles/vim/plugged/gruvbox/gruvbox_256palette.sh"
#fzf import
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# Disable Highlight with underline
(( ${+ZSH_HIGHLIGHT_STYLES} )) || typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none
# Accept Widgets for ZSH Autosuggestion Using Vim word foward key
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(vi-forward-char)
# Partial Accept Widgets for ZSH Autosuggestion Using Vim word foward key
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(vi-forward-word vi-forward-word-end)
# Vim key binding
bindkey -v
bindkey "^R" fzf-history-widget
# Source customized function
source ~/.zsh_custom_commands.sh
# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)
setopt extended_glob
# Check if the shell is zsh
export PS1='%1~%F{yellow}$ %f'
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/ziqi/.miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/ziqi/.miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/ziqi/.miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/ziqi/.miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

