# Set up the user name
export PS1="%1~$ "
export PATH=/opt/homebrew/bin:$PATH
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

alias docker="/Applications/Docker.app/Contents/Resources/bin/docker"
# Source all the zsh plugins from .cfg/zsh_plugins/*
source "$HOME/.cfg/zsh_plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh"
source "$HOME/.cfg/zsh_plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$HOME/.cfg/zsh_plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# Accept Widgets for ZSH Autosuggestion Using Vim word foward key
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(vi-forward-char)
# Partial Accept Widgets for ZSH Autosuggestion Using Vim word foward key
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(vi-forward-word vi-forward-word-end)
# Vim key binding
bindkey -v
bindkey "^H" backward-delete-char
bindkey "^?" backward-delete-char
# Color for vim
source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"
# Source customized function
source ~/.zsh_custom_commands.sh
# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)
